### ISSUE TITLE
7-zip dll 

### ISSUE THREAD

**Issue by asharkman** [wqweto/VszLib#1]
Hi, 

I'm using vb6 on win 7 PC. I've regestered the DLL, but when i try run the sample i get 7-zip dll not round. I'm trying to unzip a zip file. 

Any ideas?

Cheers,

**Comment by wqweto** [comment]
This component is using 7-zip to do the actual compression. You'll need to either have 7-zip installed on client PCs or ship `7z.dll` (or the smaller `7za.dll` from [7-zip extras](http://sourceforge.net/projects/sevenzip/files/7-Zip/9.22/7z922_extra.7z/download)) along with `VszLib.dll` and deploy both to the same folder.

Note that `7za.dll` can only handle `.7z` archives, so you'll need `7z.dll` for `.zip` support (and every other format 7-zip supports)

**Comment by asharkman** [comment]
That was perfect, cheers for that. i put the dll in the same folder, as the instructions actually state, so apologies for the question! 

I was wondering if you could assist with the password portion. I added the password to a zip file through winzip, the app unzips the file but the content of the text file is empty. Even if the password is incorrect. I can't seem to get it to raise an error. 

Cheers,

**Comment by wqweto** [comment]
> I can't seem to get it to raise an error.

`cVszArchive` instance raises **event** `Error` (besides `Progress` event). So you can organize some user input in your application when the error text is something like _Data Error. Wrong password?_.

Also try to skip "errors" with _User cancelled_ in the body as these are generated by the original 7-zip dll when you set `Cancel = True` in `Progress` event.

**Comment by asharkman** [comment]
Hi, 

Ok, I added with events to my object, I then put in an incorrect password and that raised an error Unknown error: 9. So that's great. 

If i put the correct password in, it doesn't raise an error though. Just carries on through. 
I don't quite follow what you mean regards the cancel event, i can see the progress event being hit, but not sure what to once it's hit. 

Cheers for the help.

**Comment by wqweto** [comment]
_Unknown error: 9_ is a weird one. Don't know why you don't get a better message. Which version of 7-zip did you use for the companion dll?

In `Progress` you can usually `DoEvents` to keep the UI responsive and then set a flag `m_bCancelled` in a `Click` event of a button. The idea is in `Progress` to check if this flag set and in turn set `Cancel = True` before returning control to 7-zip (`Cancel` is a `ByRef` out param)

**Comment by asharkman** [comment]
Hey,


7z.dll is version 15.14.0.0. I'll try get a different one and give that a shot. Using win7, 64bit. Not sure if that'd make a difference.



Cheers,
Paul.

![7z](https://cloud.githubusercontent.com/assets/12616302/14485900/e47f1f10-0151-11e6-8754-1303f1510ca2.png)

**Comment by asharkman** [comment]
Hey,

Got it working, i used an earlier version of 7z.dll, and BOOM it works! 
I'm able to unzip files with passwords and i'm able to get an error message back when incorrect password is used.

Listen thank you for your help on this!

Cheers,


![7z](https://cloud.githubusercontent.com/assets/12616302/14488199/cd660bce-015e-11e6-82e8-eb9e50ad279a.png)

**Comment by wqweto** [comment]
Ahaaa, so newer versions of 7-zip are not working.

I'm planning a complete rewrite for VszLib 2.0 (recompile from original C/C++ sources with no external companion DLL) so this will get taken care of then.
