### ISSUE TITLE
Create ZIP archive

### ISSUE THREAD

**Issue by Seniorchef** [wqweto/VszLib#4]
Sample don't work, creates no zip-archive:

With New cVszArchive
    .AddFile "your_file"
    '--- store filenames in UTF-8
    .Parameter("cu") = "on"
    .CompressArchive "archive.zip"
End With

Are any additional commands needed to create a Zip instead of a 7z?

Regards
Jo (seniorchef)

**Comment by wqweto** [comment]
You can use `Init` method to specify "c:\path\to\7z.dll" version 9.22 which works well with VszLib.

Check out [this](https://www.vbforums.com/showthread.php?891156-Question-How-to-pack-files-xml-with-the-format-TAR-in-Visual-Basic-6&p=5516312&viewfull=1#post5516312) forum post.

**Comment by Seniorchef** [comment]
The version of the dll is the key: The last dll supporting zip is in 7z1604, downloaded from sourceforge.
Works like a charm, even with zip-archives >2gb!
Thank's a lot, Vladimir!
